
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE user(
	id_user INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	twitter VARCHAR(100),
	password VARCHAR(100) NOT NULL,
	image VARCHAR(300),
	valid BOOLEAN DAFAULT false,
	PRIMARY KEY (id_user)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=54;
